apiVersion: v1
kind: Service
metadata:
  name: dev-ops-react
  labels:
    app: dev-ops-react
spec:
  type: LoadBalancer
  selector:
    app: dev-ops-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

 